#!/bin/sh
# Add your startup script

# DO NOT DELETE
echo $FLAG > /home/ctf/flag

# Dynamic flag generated by CTFd-whale
chown root:ctf /home/ctf/flag

# start ctf-xinetd
/etc/init.d/xinetd start; 
trap : TERM INT; 
sleep infinity & wait
